### ISSUE TITLE
Saving filtered data renames the frame but does not update window_zorder

### ISSUE THREAD

**Issue by MrMabogo** [uvaKCCI/flimanalyzer#16]
**To recreate:**
1. Open any data set
2. Filter out any data with Filter Settings
3. Save All under a new name
4. Try to run analysis on the filtered data

**Details:**
The cause is [gui/app.py](https://github.com/uvaKCCI/flimanalyzer/blob/main/flim/gui/app.py#L965) line 965:
```python
return self.windowframes[self.window_zorder[-1]].GetViewData()
```
The key at window_zorder[-1] does not exist in windowframes. When the original frame is renamed, the change needs to also be reflected in window_zorder.

**Comment by ksiller** [comment]
fixed.
