### ISSUE TITLE
Frequency histogram always has 51 bins

### ISSUE THREAD

**Issue by MrMabogo** [uvaKCCI/flimanalyzer#21]
Regardless of the number of bins selected in the dialog, the binned data table always shows 51 bins.

**Comment by ksiller** [comment]
This is due to some legacy handling of feature-specific range and binning configs in freqhisto.py.  We could comment out this try/except block but then the dialog settings would apply to all selected features in the same way.
            try:
                hconfig = self.params[header]
                mrange = (hconfig[0], hconfig[1])
                bins = hconfig[2]
            except:
                logging.debug(f"\tmissing binning parameters, using defaults.")

**Comment by MrMabogo** [comment]
So the way I'm understanding it right now is each feature has its own associated range & binning configs and there is no way to change that from interacting with the normal config windows. The dialog settings would take precedence if not for that try/except block. Is that right?

**Comment by ksiller** [comment]
Correct.  We could modify the dialog to show a table/listctrl, each row representing one feature and columns to handle a selection checkbox, range min, range max, and # of bins.

**Comment by MrMabogo** [comment]
That explains why the default aligns with what Horst usually does for NADPH. That solution sounds like a good idea. Since the defaults align with the current workflow, I can put this on the backburner and ask how they would want this to be resolved then work from there.
