### ISSUE TITLE
No mean bar plots when grouping by more than 3 groups

### ISSUE THREAD

**Issue by ksiller** [uvaKCCI/flimanalyzer#5]

**Comment by ksiller** [comment]
From Horst:
Note: Each FoV has linked, different number of cells with data associated to FoV
1.With both Compartments, FoV-a, all treatments & cells activated in Data Master the ROI Grouping is ‘Compartment_Fov_Cell_Treatment’ [Karsten? did not work] Does thag mean you got an error message/crash?
2.With both Compartments, FoV-a, ’treatment- Ctrl’ (only) & cells activated in Data Master, the ROI Grouping is ‘Compartment_Fov_Cell_Treatment’ [Karsten? did not work either, so it is not the RAM on my computer] Does that mean you got an error message/crash?
3.With both Compartments, FoV-a, cells activated in Data Master, the ROI Grouping is ‘Compartment_FoV_Cells [This worked!]

**Comment by ksiller** [comment]
![Screen Shot 2020-12-11 at 4 26 05 AM](https://user-images.githubusercontent.com/7979690/101886466-85f59080-3b69-11eb-931b-554533a26f00.png)
![Screen Shot 2020-12-11 at 4 21 55 AM](https://user-images.githubusercontent.com/7979690/101886467-868e2700-3b69-11eb-92c9-6fb985dad133.png)

**Comment by MrMabogo** [comment]
Couldn't reproduce. Horst said he may have done something wrong initially.
