### ISSUE TITLE
Remove leading zeroes from cell labels

### ISSUE THREAD

**Issue by ksiller** [uvaKCCI/flimanalyzer#7]

**Comment by MrMabogo** [comment]
I'll take a look at this. Are there any parts that depend on these leading zeroes? I'm especially concerned about the file name parsers...

**Comment by ksiller** [comment]
All category columns use object as type for their discrete values.  It is one of the identifying characteristics for defining the grouping options.  After stripping the leading zeroes, the column values should remain objects rather than ints or floats.  That will affect default sorting though (1,10,11,2,20,21,22,3,30,31...) unless we define a custom sorting function.

**Comment by MrMabogo** [comment]
I assume this is because the sorting criteria are different for generic objects vs. strings vs. any type of numbers. Also, this would be more of a usability thing as current analyses don't care about cell sorting right?

**Comment by ksiller** [comment]
Correct.
